# Generated by Django 4.0.4 on 2022-10-14 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50, "can't be a weakling!"), django.core.validators.MaxValueValidator(350, "can't be a God!")]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('WA', 'Water'), ('GR', 'Grass'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=2),
        ),
    ]
